# Generated by Django 3.0.8 on 2020-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetschema',
            name='tweet_external_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
