# Generated by Django 3.0.8 on 2020-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweetschema_tweet_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetschema',
            options={'ordering': ('tweet_create_time',)},
        ),
        migrations.AlterField(
            model_name='tweetschema',
            name='tweet_external_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
