# Generated by Django 3.0.8 on 2020-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20200819_1244'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetschema',
            index=models.Index(fields=['tweet_external_id'], name='tweets_tweet_e_1df457_idx'),
        ),
    ]
