# Generated by Django 3.0.8 on 2020-08-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0002_auto_20200818_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrationschema',
            name='previous_concentration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concentration.ConcentrationSchema'),
        ),
    ]
