# Generated by Django 3.0.8 on 2020-08-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0003_concentrationschema_previous_concentration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concentrationschema',
            options={'ordering': ('calculation_date',)},
        ),
    ]
