# Generated by Django 3.0.8 on 2020-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='A', max_length=3)),
                ('suggestion_date', models.DateField()),
                ('previous_concentraion', models.FloatField()),
                ('current_concentraion', models.FloatField()),
                ('suggestion', models.IntegerField()),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ('created_on',),
            },
        ),
    ]
