# Generated by Django 3.0.8 on 2020-08-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0003_concentrationschema_previous_concentration'),
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionschema',
            name='current_concentraion',
        ),
        migrations.RemoveField(
            model_name='suggestionschema',
            name='previous_concentraion',
        ),
        migrations.AddField(
            model_name='suggestionschema',
            name='concentration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concentration.ConcentrationSchema'),
        ),
    ]
