# Generated by Django 3.0.8 on 2020-08-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20200819_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionschema',
            options={'ordering': ('suggestion_date',)},
        ),
    ]
